# Generated by Django 3.2.5 on 2021-07-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secrete_key', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
