# Generated by Django 3.2.5 on 2021-07-26 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.PositiveIntegerField(blank=True, null=True)),
                ('prime', models.PositiveIntegerField(blank=True, null=True)),
                ('sender_partial_key', models.PositiveIntegerField(blank=True, null=True)),
                ('reciever_partial_key', models.PositiveIntegerField(blank=True, null=True)),
                ('sender_private_integer', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('reciever_private_integer', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)])),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
