# Generated by Django 3.2.5 on 2021-07-21 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchangeApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_reciever', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_sender', to='users.customuser'),
        ),
    ]
