# Generated by Django 3.2.5 on 2021-07-22 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeApp', '0004_alter_exchange_sender_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='base',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='prime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='reciever_partial_key',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='reciever_private_key',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sender_partial_key',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='sender_private_key',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
